name: Build iOS MAUI App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0' 
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: dotnet workload install maui ios --source https://aka.ms/dotnet9/nuget/microsoft-net-components-toolset
    - run: dotnet restore Calculator.sln
    - run: |
        dotnet build Calculator.iOS.csproj \
          -f net9.0-ios15.0 \
          -c Release \
          /p:TargetPlatformVersion=15.0 \
          /p:ArchiveOnBuild=true
    - uses: actions/upload-artifact@v4
      with:
        name: iOS-IPA
        path: '**/bin/Release/net9.0-ios15.0/*.ipa'